import "./globals.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Providers from "@/components/Providers";
import SessionRestore from "@/components/SessionRestore";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "taskOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="taskOS" />
      </head>
      <body className={`${inter.variable}`}>
        <Providers>
          <SessionRestore>{children}</SessionRestore>
        </Providers>
      </body>
    </html>
  );
}
